name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^6.2.1
  uuid: ^4.4.2
  mongo_dart: ^0.10.3
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

fonts:
- family: WorkSans
  fonts:
    - asset: fonts/WorkSans/WorkSans-Regular.ttf

    - asset: fonts/WorkSans/WorkSans-Medium.ttf
      weight: 400

    - asset: fonts/WorkSans/WorkSans-SemiBold.ttf
      weight: 600

    - asset: fonts/WorkSans/WorkSans-Bold.ttf
      weight: 800

flutter:
  uses-material-design: true